[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/run"
  to = "/.netlify/functions/run"
  status = 200
